"""
core.mission_manager
=======================

Missions/Gamification — docs/ROADMAP.md milestone v0.18, the second of
three new subsystems from the 2026-07-14 wearable-companion vision
update (see docs/VISION.md). Turns a stated goal/hobby into a tracked
Mission with one or more Objectives (e.g. a "Master Angler" mission for
a fishing trip: one objective for time spent fishing, one for fish
caught). Same persisted-JSON pattern as core/expedition_manager.py:
data/missions.json, dataclasses with to_dict/from_dict, a manager class
wrapping load/save. `Objective` is nested inside `Mission`'s own JSON,
not a separate top-level record — same reasoning as `GearItem`/`Split`
nested inside `Trip` (core/trip_manager.py): an objective only ever
makes sense in the context of one mission.

A Mission optionally links to an existing `core.trip_manager.Trip` via
`trip_id` (mirrors `JournalEntry.trip_id`'s optional-FK pattern) —
`trip_id=None` supports a general goal not tied to any specific outing
("finish wiring the garage"), not just outdoor Trip-scoped ones.
`task_id` is the same idea for `core.task_manager.Task` — used only by
`check_for_auto_assignment()`'s "stale task" rule below.

Three objective metric types (`METRIC_TYPES`, same fixed-vocabulary
pattern as `ACTIVITY_TYPES`):
- `"tally"` — a manually-incremented counter (fish caught, species
  identified, etc.) — the one genuinely new primitive this milestone
  needed, since nothing else in the app models an arbitrary count.
  `Objective.progress` stores this directly.
- `"trip_duration_hours"` — computed on demand from the linked Trip's
  logged splits (first-to-last-split elapsed time), never stored, so
  it can't go stale — same "compute on demand" philosophy as
  core/memory_manager.py's ExpeditionRecap. Requires the Mission to
  have a `trip_id` and that Trip to have at least 2 logged splits;
  reads as 0.0 (not started) otherwise rather than raising, since an
  objective with no progress yet is a normal, expected state.
- `"task_done"` — same "compute on demand, never stored" philosophy as
  `trip_duration_hours`, reading the linked `core.task_manager.Task`
  (via the Mission's `task_id`)'s `done` flag as 1.0/0.0. Only ever
  produced by `check_for_auto_assignment()`'s "stale task" rule — there
  is no UI for a user to create one of these by hand, since a task's
  own checkbox is already the natural way to mark it done.

**2026-07-16 gamification pass** (docs/VISION.md's "gamifying life"
goal, at the user's explicit request: "MIA should assign me missions
sometimes... there's not much fun in having to assign yourself
missions"): `Mission.assigned_by` ("user" | "mia") records whether a
Mission was hand-created via modules/missions/module.py's "Add Mission"
button or auto-generated by `check_for_auto_assignment()`, so
gui/widgets/mission_card.py can show a distinct badge for the latter.

`check_for_auto_assignment()` is deliberately rule-based, not
LLM-driven — CLAUDE.md's "no AI/assistant logic yet" scope (ROADMAP
phase v0.5) rules out anything smarter for now, and a handful of
deterministic, fully-offline, testable-without-a-model rules already
satisfy "MIA assigns me missions sometimes":

1. **Idle rule**: if there's no currently-active mission, and either no
   mission has ever been auto-assigned before or it's been at least
   `_AUTO_ASSIGN_IDLE_DAYS` since the last one was, MIA picks the next
   not-yet-used template from `_AUTO_MISSION_TEMPLATES` (cycling back to
   the start once every template has been used at least once) and
   assigns it.
2. **Stale task rule**: otherwise, if `context.tasks` is available, MIA
   looks for the least-recently-updated incomplete Task that isn't
   already wrapped by an existing Mission's `task_id`, and — only once
   it's sat untouched for at least `_STALE_TASK_DAYS` — turns it into a
   one-objective Mission (`metric_type="task_done"`), so a task that's
   been quietly ignored gets a nudge as "MIA turning it into a quest"
   rather than the user having to notice and self-assign it.

Only one Mission is auto-assigned per `check_for_auto_assignment()`
call (whichever rule fires first), and it's driven off dates already
stored on real records (mission/task `created_at`/`updated_at`) rather
than a new "last checked" timestamp — same "derive it, don't add a new
field to track it" preference as `core/daily_occasions.py`'s own
once-daily gates use the target date field itself, not a separate
counter.

**Group quests (2026-09-14)** — the multi-user vision handoff's own
"D&D-style party system" (see the `project_mia_multiuser_vision`
memory), section 5: "Prepare the House for Fall," with Zac's own
objectives, Faith's own, and shared ones, tracked under one Mission.
`Mission.participant_profile_ids` (empty by default — every existing
Mission, and any ordinary solo Mission still) names the real party;
`Objective.assigned_profile_id` (also `None`-default) marks a specific
objective as personal to one participant rather than shared/anyone's.
`individual_objective_progress()`/`group_objective_progress()` derive
the vision doc's own "Your Contribution: 4/7" and "Household Progress:
68%" numbers live from real objective completion state — nothing new
persisted. `_credit_mission_rewards()` grants the Mission's flat
reward to EVERY participant on completion when the list is real, not
just whoever happened to click complete — "group rewards." Deliberately
NOT built this pass: automatic per-objective reward splitting (there's
no per-objective reward_xp field, only the Mission's own flat one) —
a real, separate future refinement if the flat "everyone gets the same
reward" model ever feels wrong in practice.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.app_context import AppContext
from core.gamification import SkillWeight, grant_xp
from core.logger import get_logger

log = get_logger(__name__)

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_MISSIONS_FILE = _DATA_DIR / "missions.json"

METRIC_TYPES: tuple[str, ...] = ("tally", "trip_duration_hours", "task_done")

# check_for_auto_assignment()'s two rule thresholds — see this module's
# own "2026-07-16 gamification pass" docstring section above.
_AUTO_ASSIGN_IDLE_DAYS = 3
_STALE_TASK_DAYS = 5

# Flavorful, fully self-contained (no other manager needed) mission
# templates for the "idle" auto-assignment rule — deliberately generic
# life-gamification goals rather than anything tied to a specific
# module, since check_for_auto_assignment() has no way to know what the
# user actually cares about right now without real AI/assistant logic
# (out of scope — see CLAUDE.md). Each entry: (name, [(description,
# metric_type, target), ...]) — always "tally" here since these have no
# linked Trip/Task to compute a live metric from.
_AUTO_MISSION_TEMPLATES: tuple[tuple[str, tuple[tuple[str, str, float], ...]], ...] = (
    (
        "Digital Declutter",
        (("Clear out 10 old files, photos, or downloads you no longer need", "tally", 10.0),),
    ),
    (
        "Deep Work Streak",
        (("Log 3 focused work sessions with no distractions", "tally", 3.0),),
    ),
    (
        "Tidy Up",
        (("Straighten up 3 areas of your space", "tally", 3.0),),
    ),
    (
        "Move Your Body",
        (("Get up and move around 5 separate times today", "tally", 5.0),),
    ),
    (
        "Inbox Zero Push",
        (("Clear 15 messages/emails out of your inbox", "tally", 15.0),),
    ),
)


@dataclass
class Objective:
    description: str  # e.g. "Catch 3 fish" or "Spend 2 hours fishing"
    metric_type: str  # one of METRIC_TYPES
    target: float
    progress: float = 0.0  # only meaningful for "tally" — "trip_duration_hours" is always computed live, never stored here
    # Group quests (2026-09-14, per the user's own multi-user vision
    # handoff, section 5 — "Prepare the House for Fall": Zac's own
    # objectives, Faith's own, plus shared ones). None (the default,
    # every existing objective included) means "shared" — anyone on
    # the quest can work it, and it counts toward group progress only.
    # A real profile_id makes it personal to that one participant —
    # counted in BOTH their own individual progress
    # (MissionManager.individual_objective_progress()) and the whole
    # mission's group progress (MissionManager.group_objective_progress()).
    assigned_profile_id: Optional[str] = None

    def to_dict(self) -> dict:
        return {
            "description": self.description,
            "metric_type": self.metric_type,
            "target": self.target,
            "progress": self.progress,
            "assigned_profile_id": self.assigned_profile_id,
        }

    @staticmethod
    def from_dict(data: dict) -> "Objective":
        return Objective(
            description=data.get("description", ""),
            metric_type=data.get("metric_type", "tally"),
            target=float(data.get("target", 0.0)),
            progress=float(data.get("progress", 0.0)),
            assigned_profile_id=data.get("assigned_profile_id"),
        )


#: Suggested vocabulary for Mission.difficulty — a plain str, not an
#: enum, same "unrecognized/blank just means unspecified" reasoning as
#: core/trip_manager.py's ACTIVITY_TYPES.
DIFFICULTY_LEVELS: tuple[str, ...] = ("EASY", "NORMAL", "HARD")

#: Suggested vocabulary for Mission.abandon_reason (2026-09-11, the
#: "mission failure/struggle signal" pass) — same "unrecognized/blank
#: just means unspecified" spirit as DIFFICULTY_LEVELS above, not a
#: hard-enforced enum. "too_hard" is the one core/discovery_manager.py
#: actually looks for (a real signal that a skill area needs an easier
#: or prerequisite step next) — the others exist so the reason is at
#: least recorded, even though nothing reacts to them yet.
ABANDON_REASONS: tuple[str, ...] = ("too_hard", "not_interested", "no_time", "other")


@dataclass
class Mission:
    mission_id: str
    name: str
    trip_id: Optional[str] = None
    task_id: Optional[str] = None
    # Connective-infrastructure pass (2026-09-11) — a Mission can
    # optionally be the gamified "face" of a Project, rather than the
    # two staying two unrelated containers for structured work. None
    # by default (zero migration needed for existing data/missions.json)
    # and, deliberately, not settable through update_mission() once a
    # Mission exists — same "pick it at creation, don't reassign later"
    # rule trip_id already follows.
    project_id: Optional[str] = None
    status: str = "active"  # "active" | "completed" | "abandoned"
    # The "mission failure/struggle signal" pass (2026-09-11) — why an
    # abandoned mission was abandoned, one of ABANDON_REASONS above (or
    # "" — no reason recorded, e.g. every mission abandoned before this
    # field existed). Only meaningful when status == "abandoned"; see
    # gui/add_edit_mission_dialog.py for how the UI keeps a stray value
    # here from sticking to a mission that isn't actually abandoned.
    abandon_reason: str = ""
    assigned_by: str = "user"  # "user" | "mia" — see module docstring's "2026-07-16 gamification pass"
    objectives: list[Objective] = field(default_factory=list)
    created_at: str = ""  # ISO datetime
    updated_at: str = ""  # ISO datetime
    # 2026-07-18 design handoff (CCH.zip's Mission Log screen) — cosmetic/
    # gamification fields the redesigned Missions module surfaces.
    # `region` is a short mono "eyebrow" label (e.g. "FIELD SEASON ·
    # FISHING"), not a real geographic region — free text, same "just a
    # label" spirit as Trip.activity_type.
    icon: str = "\U0001F4CB"  # clipboard, matches this project's emoji-glyph convention (no image assets)
    region: str = ""
    summary: str = ""  # longer descriptive paragraph, shown on the Mission Log detail card
    difficulty: str = "NORMAL"
    mission_type: str = "OPTIONAL MISSION"  # e.g. "OPTIONAL MISSION", "DAILY MISSION" — free text, shown as-is
    reward_xp: int = 0
    reward_credits: int = 0
    # "My Hero's Path" (2026-09-11) — optional per-skill XP a completed
    # Mission also grants, alongside its existing flat reward_xp, via
    # the same core.gamification.grant_xp() path every routine-
    # completion hook already uses. Empty by default: every Mission
    # created before this pass deserializes with skill_rewards=[] and
    # behaves exactly as it did — no migration needed. Same "a record
    # owns its own nested list of sub-items" shape as `objectives`
    # above, not a separate top-level manager.
    skill_rewards: list[SkillWeight] = field(default_factory=list)
    # "Recipe Unlocked" (2026-09-12) — real core.kitchen_manager.Recipe
    # ids to unlock (Recipe.locked -> False) on this Mission's real
    # completion. Empty by default, zero migration needed. Credited
    # independently of skill_rewards/reward_xp — see
    # MissionManager._unlock_mission_recipes().
    recipe_unlocks: list[str] = field(default_factory=list)
    # Design restyle, Phase 3 (2026-09-12) — the Sensor Monitor screen's
    # "START QUEST" button on a crossed-threshold MaintenanceTask
    # (core.maintenance_manager) needs to find-or-create exactly one
    # Mission per task, same optional-FK shape trip_id already
    # establishes above (picked at creation, not reassignable via
    # update_mission()). None by default — zero migration needed.
    maintenance_task_id: Optional[str] = None
    # "Manage Skills" UI (2026-09-12) — True once this Mission's
    # reward_xp/reward_credits/skill_rewards have been bulk-credited at
    # least once. Real, not speculative: Mission's own status combo
    # (gui/add_edit_mission_dialog.py) lets a user set a completed
    # Mission back to "active" and complete it again — without this
    # flag, that real, reachable cycle would re-grant every reward each
    # time (the same exploit core.project_manager.Project's own
    # skill_weights_credited already guards against — its comment used
    # to claim Mission's status has "no going back," which is wrong).
    # Never reset once True. Doesn't gate add_skill_reward()'s own
    # single-new-weight crediting path — that one's safe by
    # construction (it only ever credits the ONE weight just appended).
    rewards_credited: bool = False
    # Recurring Missions (2026-09-13) — same optional-FK shape as
    # maintenance_task_id above. A Mission created by
    # core.recurring_mission_manager.RecurringMissionManager carries all
    # three: which template it came from, whether it's the "daily"
    # occurrence or the week's "weekly" summary/bonus, and a stable key
    # identifying *which* occurrence (the daily one's real ISO date, or
    # the weekly one's "{start_date}-Wn") so ensure_current_missions()
    # can look up "does this occurrence already exist" without any date
    # parsing of created_at. None for every ordinary Mission.
    recurring_template_id: Optional[str] = None
    recurring_kind: Optional[str] = None  # "daily" | "weekly"
    occurrence_key: Optional[str] = None
    # Mission-to-asset tagging (2026-09-13) — same optional-FK shape as
    # maintenance_task_id above, but pointing at the whole
    # MaintenanceAsset rather than one specific recurring task on it: a
    # Mission can be generally "about" a house/mower/truck/greenhouse
    # asset (e.g. "Clean Out the Old House") without being tied to any
    # one task. Surfaced by gui/widgets/asset_missions_panel.py on
    # whichever real per-area module (Garage/Real Estate/Greenhouse)
    # owns that asset's category.
    maintenance_asset_id: Optional[str] = None
    # Per-profile rewards (2026-09-14) — the user's own ask ("she will
    # obviously have profile specific missions and maybe not have some
    # of the same ones I have too"). None (the default, every existing
    # Mission included) means "shared/unattributed" — counts toward
    # EVERY profile's missions_completed, same as before this field
    # existed. Settable at creation for real forward-planning
    # ("assign this Mission to Faith"); otherwise auto-stamped with
    # whoever's active the moment it's genuinely completed (see
    # update_mission() below) — same "credit whoever's actually active"
    # precedent core.gamification.grant_xp() already follows for XP,
    # so a Mission naturally becomes whoever's real accomplishment
    # completed it, with zero new assignment UI required.
    profile_id: Optional[str] = None
    # Group quests (2026-09-14) — the real party members on this
    # Mission, e.g. "Prepare the House for Fall" with both Zac and
    # Faith. Empty (the default, every existing Mission included) means
    # a normal solo/unattributed Mission — completely unchanged
    # behavior. When non-empty: _credit_mission_rewards() grants the
    # flat reward_xp/reward_credits/skill_rewards to EVERY participant
    # on completion (not just whoever was active), and
    # core.rewards_manager's missions_completed stat counts it for
    # every participant too — "the mission can have... group rewards,"
    # the user's own words.
    participant_profile_ids: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "mission_id": self.mission_id,
            "name": self.name,
            "trip_id": self.trip_id,
            "task_id": self.task_id,
            "project_id": self.project_id,
            "status": self.status,
            "abandon_reason": self.abandon_reason,
            "assigned_by": self.assigned_by,
            "objectives": [o.to_dict() for o in self.objectives],
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "icon": self.icon,
            "region": self.region,
            "summary": self.summary,
            "difficulty": self.difficulty,
            "mission_type": self.mission_type,
            "reward_xp": self.reward_xp,
            "reward_credits": self.reward_credits,
            "skill_rewards": [{"skill_id": w.skill_id, "xp": w.xp} for w in self.skill_rewards],
            "recipe_unlocks": list(self.recipe_unlocks),
            "maintenance_task_id": self.maintenance_task_id,
            "rewards_credited": self.rewards_credited,
            "recurring_template_id": self.recurring_template_id,
            "recurring_kind": self.recurring_kind,
            "occurrence_key": self.occurrence_key,
            "maintenance_asset_id": self.maintenance_asset_id,
            "profile_id": self.profile_id,
            "participant_profile_ids": list(self.participant_profile_ids),
        }

    @staticmethod
    def from_dict(data: dict) -> "Mission":
        return Mission(
            mission_id=data.get("mission_id", uuid.uuid4().hex[:10]),
            name=data.get("name", ""),
            trip_id=data.get("trip_id"),
            task_id=data.get("task_id"),
            project_id=data.get("project_id"),
            status=data.get("status", "active"),
            abandon_reason=data.get("abandon_reason", ""),
            assigned_by=data.get("assigned_by", "user"),
            objectives=[Objective.from_dict(d) for d in data.get("objectives", [])],
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at", ""),
            icon=data.get("icon", "\U0001F4CB"),
            region=data.get("region", ""),
            summary=data.get("summary", ""),
            difficulty=data.get("difficulty", "NORMAL"),
            mission_type=data.get("mission_type", "OPTIONAL MISSION"),
            reward_xp=data.get("reward_xp", 0),
            reward_credits=data.get("reward_credits", 0),
            skill_rewards=[
                SkillWeight(skill_id=d["skill_id"], xp=d["xp"]) for d in data.get("skill_rewards", [])
            ],
            recipe_unlocks=list(data.get("recipe_unlocks", [])),
            maintenance_task_id=data.get("maintenance_task_id"),
            rewards_credited=bool(data.get("rewards_credited", False)),
            recurring_template_id=data.get("recurring_template_id"),
            recurring_kind=data.get("recurring_kind"),
            occurrence_key=data.get("occurrence_key"),
            maintenance_asset_id=data.get("maintenance_asset_id"),
            profile_id=data.get("profile_id"),
            participant_profile_ids=list(data.get("participant_profile_ids", [])),
        )


class MissionManager:
    def __init__(self, context: AppContext) -> None:
        self.context = context
        self._missions: list[Mission] = []
        self._load()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load(self) -> None:
        if not _MISSIONS_FILE.exists():
            self._missions = []
            return
        try:
            raw = json.loads(_MISSIONS_FILE.read_text(encoding="utf-8"))
            self._missions = [Mission.from_dict(d) for d in raw]
        except (json.JSONDecodeError, OSError):
            log.exception("Failed to load missions.json — starting with an empty list.")
            self._missions = []

    def _save(self) -> None:
        _DATA_DIR.mkdir(parents=True, exist_ok=True)
        _MISSIONS_FILE.write_text(
            json.dumps([m.to_dict() for m in self._missions], indent=2),
            encoding="utf-8",
        )

    def _bump_updated_at(self, mission: Mission) -> None:
        mission.updated_at = datetime.now().isoformat(timespec="seconds")

    # ------------------------------------------------------------------
    # Mission CRUD
    # ------------------------------------------------------------------

    def add_mission(
        self,
        name: str,
        trip_id: Optional[str] = None,
        task_id: Optional[str] = None,
        project_id: Optional[str] = None,
        assigned_by: str = "user",
        icon: str = "\U0001F4CB",
        region: str = "",
        summary: str = "",
        difficulty: str = "NORMAL",
        mission_type: str = "OPTIONAL MISSION",
        reward_xp: int = 0,
        reward_credits: int = 0,
        skill_rewards: Optional[list[SkillWeight]] = None,
        recipe_unlocks: Optional[list[str]] = None,
        maintenance_task_id: Optional[str] = None,
        recurring_template_id: Optional[str] = None,
        recurring_kind: Optional[str] = None,
        occurrence_key: Optional[str] = None,
        maintenance_asset_id: Optional[str] = None,
        profile_id: Optional[str] = None,
        participant_profile_ids: Optional[list[str]] = None,
    ) -> Mission:
        now = datetime.now().isoformat(timespec="seconds")
        mission = Mission(
            mission_id=uuid.uuid4().hex[:10],
            name=name,
            trip_id=trip_id,
            task_id=task_id,
            project_id=project_id,
            assigned_by=assigned_by,
            created_at=now,
            updated_at=now,
            icon=icon,
            region=region,
            summary=summary,
            difficulty=difficulty,
            mission_type=mission_type,
            reward_xp=reward_xp,
            reward_credits=reward_credits,
            skill_rewards=list(skill_rewards) if skill_rewards else [],
            recipe_unlocks=list(recipe_unlocks) if recipe_unlocks else [],
            maintenance_task_id=maintenance_task_id,
            recurring_template_id=recurring_template_id,
            recurring_kind=recurring_kind,
            occurrence_key=occurrence_key,
            maintenance_asset_id=maintenance_asset_id,
            profile_id=profile_id,
            participant_profile_ids=list(participant_profile_ids) if participant_profile_ids else [],
        )
        self._missions.append(mission)
        self._save()
        log.info("Mission added: '%s'", name)
        return mission

    def update_mission(self, mission_id: str, **fields) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        was_completed = mission.status == "completed"
        was_abandoned = mission.status == "abandoned"
        for key, value in fields.items():
            if key in ("created_at", "trip_id", "project_id", "rewards_credited"):
                raise ValueError(f"'{key}' can't be set through update_mission().")
            if not hasattr(mission, key):
                raise ValueError(f"Mission has no field '{key}'.")
            setattr(mission, key, value)
        self._bump_updated_at(mission)
        self._save()
        # Fires uniformly whether "completed" was set via
        # modules/missions/module.py's own UI button or the Assistant's
        # complete_mission action (core/application.py) — celebration
        # logic lives here, in the manager, so neither call site needs
        # its own copy of "did this just newly become complete."
        if not was_completed and mission.status == "completed":
            # Per-profile rewards (2026-09-14) — a Mission created with
            # no explicit owner becomes whoever's real accomplishment
            # completed it, the first time it's genuinely completed
            # (never reassigned on a later re-completion — same "pick
            # it once" rule trip_id/project_id already follow). See
            # Mission.profile_id's own docstring.
            if mission.profile_id is None and self.context.profiles is not None:
                active_profile = self.context.profiles.get_active_profile()
                if active_profile is not None:
                    mission.profile_id = active_profile.profile_id
            self._notify_mission_completed(mission)
            # "Manage Skills" UI (2026-09-12) — reward-crediting
            # specifically (not the notify/recipe-unlock/event-publish
            # below) is additionally gated on rewards_credited: a
            # completed Mission's status can genuinely go back to
            # "active" via gui/add_edit_mission_dialog.py's own status
            # combo, and without this guard re-completing would
            # re-grant every reward every time (a real exploit vector,
            # not theoretical — see Mission.rewards_credited's own
            # docstring). The other three effects below are left firing
            # on every genuine completion transition, unchanged —
            # narrower fix, not a broader behavior change to Pathways/
            # Recipe-unlock semantics that weren't part of this bug.
            if not mission.rewards_credited:
                self._credit_mission_rewards(mission)
                mission.rewards_credited = True
                # A second save — the one above already ran before this
                # block, so without this the flag would only ever live
                # in memory and never actually persist (caught by this
                # feature's own regression test, not assumed correct).
                self._save()
            # "Recipe Unlocked" (2026-09-12) — deliberately a separate
            # call, not folded into _credit_mission_rewards(): that
            # method's own early-return is about profile-XP crediting
            # specifically (no active profile means no one to credit)
            # and must not gate recipe unlocking, which has nothing to
            # do with an active profile existing — Kitchen has no
            # per-profile concept at all.
            self._unlock_mission_recipes(mission)
            # Mission Pathways (2026-09-11) — a real, previously-missing
            # gap this closes independent of that feature: nothing in
            # this codebase reacted to a Mission actually finishing
            # before this. Fires exactly once, on the same real
            # transition as the celebration/reward-crediting above.
            self.context.events.publish("mission.completed", mission_id=mission.mission_id)
        # "Mission failure/struggle signal" (2026-09-11) — same
        # transition-detection shape as mission.completed above, fires
        # once per genuine active/completed -> abandoned transition
        # (and again on a later re-abandon, same re-triggering
        # semantics mission.completed already has). Lets
        # core/discovery_manager.py react to *why* without this module
        # needing to know Discovery exists.
        if not was_abandoned and mission.status == "abandoned":
            self.context.events.publish(
                "mission.abandoned", mission_id=mission.mission_id, reason=mission.abandon_reason
            )
        return mission

    def _credit_mission_rewards(self, mission: Mission) -> None:
        """
        Credits reward_xp/reward_credits to the active profile — best-
        effort, same graceful-degradation stance as everything else here
        that depends on another manager (no active profile yet, e.g.
        during first-run setup, just means no one to credit).

        "My Hero's Path" (2026-09-11): also credits mission.skill_rewards
        to context.skills, if wired — a completed Mission is a real,
        deliberate completion, not routine CRUD, so it always uses its
        own credit-and-notify logic here rather than routing through
        core.gamification.grant_xp() (which would also fire a second,
        redundant notification on top of _notify_mission_completed()'s
        own).

        Group quests (2026-09-14): when `mission.participant_profile_ids`
        is real (non-empty), the SAME flat reward goes to EVERY
        participant, not just whoever happened to be active when the
        mission's last condition completed — "group rewards," the
        user's own words. Falls back to "just the active profile" for
        every mission with no real participants (every Mission before
        this pass, and any ordinary solo Mission still), unchanged.
        """
        if self.context.profiles is None or (
            mission.reward_xp == 0 and mission.reward_credits == 0 and not mission.skill_rewards
        ):
            return
        if mission.participant_profile_ids:
            profile_ids = list(mission.participant_profile_ids)
        else:
            active_profile = self.context.profiles.get_active_profile()
            if active_profile is None:
                return
            profile_ids = [active_profile.profile_id]

        for profile_id in profile_ids:
            if mission.reward_xp:
                self.context.profiles.add_xp(profile_id, mission.reward_xp)
            if mission.reward_credits:
                self.context.profiles.add_credits(profile_id, mission.reward_credits)
            if mission.skill_rewards and self.context.skills is not None:
                for weight in mission.skill_rewards:
                    self.context.skills.add_skill_xp(profile_id, weight.skill_id, weight.xp)

    def _unlock_mission_recipes(self, mission: Mission) -> None:
        """
        "Recipe Unlocked" (2026-09-12) — unlocks every real Recipe
        mission.recipe_unlocks names, via core.kitchen_manager
        .KitchenManager.unlock_recipe() (context.kitchen), which is
        itself idempotent — never fires a duplicate notification for a
        recipe that's already unlocked. Household-wide, not gated on an
        active profile — see this method's own call site in
        update_mission() for why it's kept separate from
        _credit_mission_rewards().
        """
        if not mission.recipe_unlocks or self.context.kitchen is None:
            return
        for recipe_id in mission.recipe_unlocks:
            self.context.kitchen.unlock_recipe(recipe_id)

    def add_skill_reward(self, mission_id: str, skill_id: str, xp: int) -> Mission:
        """Declares (or retroactively adds) a skill this Mission
        rewards — "Manage Skills" UI (2026-09-12), a near-verbatim port
        of core.project_manager.ProjectManager.add_skill_weight(). If
        the Mission is still active, this weight is simply appended and
        gets credited normally when it later completes (see
        update_mission()). If the Mission is ALREADY completed, this
        credits just this one new weight immediately — never the whole
        list, so an earlier completion's already-granted rewards are
        never double-credited. Doesn't touch rewards_credited — safe by
        construction."""
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        weight = SkillWeight(skill_id=skill_id, xp=xp)
        mission.skill_rewards.append(weight)
        self._bump_updated_at(mission)
        self._save()
        if mission.status == "completed":
            grant_xp(
                self.context,
                0,
                "\U0001F4DD Skill credited!",
                f"'{mission.name}' also taught you something — crediting it now.",
                skill_weights=[weight],
            )
        return mission

    def delete_mission(self, mission_id: str) -> None:
        self._missions = [m for m in self._missions if m.mission_id != mission_id]
        self._save()

    def get_mission(self, mission_id: str) -> Optional[Mission]:
        for mission in self._missions:
            if mission.mission_id == mission_id:
                return mission
        return None

    def all_missions(self) -> list[Mission]:
        return sorted(self._missions, key=lambda m: m.created_at, reverse=True)

    def missions_for_trip(self, trip_id: str) -> list[Mission]:
        return [m for m in self._missions if m.trip_id == trip_id]

    def missions_for_maintenance_task(self, task_id: str) -> list[Mission]:
        return [m for m in self._missions if m.maintenance_task_id == task_id]

    def missions_for_maintenance_asset(self, asset_id: str) -> list[Mission]:
        return [m for m in self._missions if m.maintenance_asset_id == asset_id]

    # ------------------------------------------------------------------
    # Objectives
    # ------------------------------------------------------------------

    def add_objective(
        self, mission_id: str, description: str, metric_type: str, target: float,
        assigned_profile_id: Optional[str] = None,
    ) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if metric_type not in METRIC_TYPES:
            raise ValueError(f"Unknown metric_type '{metric_type}'.")
        mission.objectives.append(Objective(
            description=description, metric_type=metric_type, target=target,
            assigned_profile_id=assigned_profile_id,
        ))
        self._bump_updated_at(mission)
        self._save()
        return mission

    def delete_objective(self, mission_id: str, index: int) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if not (0 <= index < len(mission.objectives)):
            raise ValueError(f"Mission '{mission_id}' has no objective at index {index}.")
        del mission.objectives[index]
        self._bump_updated_at(mission)
        self._save()
        return mission

    def increment_tally(self, mission_id: str, index: int, delta: float = 1.0) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if not (0 <= index < len(mission.objectives)):
            raise ValueError(f"Mission '{mission_id}' has no objective at index {index}.")
        objective = mission.objectives[index]
        if objective.metric_type != "tally":
            raise ValueError(f"Objective '{objective.description}' is not a tally-type objective.")
        was_objective_complete = objective.progress >= objective.target
        all_were_complete = self._all_objectives_complete(mission)
        objective.progress += delta
        self._bump_updated_at(mission)
        self._save()

        is_objective_complete = objective.progress >= objective.target
        if not was_objective_complete and is_objective_complete:
            self._notify_objective_completed(mission, objective)
        if not all_were_complete and self._all_objectives_complete(mission):
            self._notify_all_objectives_completed(mission)
        return mission

    def _all_objectives_complete(self, mission: Mission) -> bool:
        """
        Uses is_objective_complete() (not a bare progress>=target check
        here) so a mixed mission — some tally objectives, some
        trip_duration_hours ones — is judged correctly on both metric
        types, not just tally's directly-stored progress.
        """
        if not mission.objectives:
            return False
        return all(
            self.is_objective_complete(mission.mission_id, index) for index in range(len(mission.objectives))
        )

    def _notify_objective_completed(self, mission: Mission, objective: Objective) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F3C6 Objective complete!",
            message=f"You did it! \"{objective.description}\" is complete on your \"{mission.name}\" mission. Keep it up!",
            level="info",
            source="missions",
        )

    def _notify_all_objectives_completed(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F3C6 All objectives complete!",
            message=f"Every objective on \"{mission.name}\" is done — amazing work! Ready to mark it complete?",
            level="info",
            source="missions",
        )

    def _notify_mission_completed(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F389 Mission complete!",
            message=f"\"{mission.name}\" is complete! That's a real achievement — what's next?",
            level="info",
            source="missions",
        )

    def objective_progress(self, mission_id: str, index: int) -> Optional[float]:
        mission = self.get_mission(mission_id)
        if mission is None or not (0 <= index < len(mission.objectives)):
            return None
        objective = mission.objectives[index]
        if objective.metric_type == "trip_duration_hours":
            if mission.trip_id is None:
                return 0.0
            return self._trip_elapsed_hours(mission.trip_id) or 0.0
        if objective.metric_type == "task_done":
            if mission.task_id is None or self.context.tasks is None:
                return 0.0
            task = self.context.tasks.get_task(mission.task_id)
            return 1.0 if (task is not None and task.done) else 0.0
        return objective.progress

    def is_objective_complete(self, mission_id: str, index: int) -> bool:
        mission = self.get_mission(mission_id)
        if mission is None or not (0 <= index < len(mission.objectives)):
            return False
        progress = self.objective_progress(mission_id, index)
        return progress is not None and progress >= mission.objectives[index].target

    # ------------------------------------------------------------------
    # Group quests (2026-09-14) — individual vs. group progress over a
    # Mission with real participant_profile_ids. See Objective.
    # assigned_profile_id's own docstring for the shared-vs-personal
    # split these both read.
    # ------------------------------------------------------------------

    def individual_objective_progress(self, mission_id: str, profile_id: str) -> tuple[int, int]:
        """(completed, total) among objectives assigned SPECIFICALLY to
        `profile_id` — the vision doc's own "Your Contribution: 4/7"
        example. Shared objectives (assigned_profile_id is None) don't
        count here — see group_objective_progress() for those."""
        mission = self.get_mission(mission_id)
        if mission is None:
            return (0, 0)
        indices = [i for i, o in enumerate(mission.objectives) if o.assigned_profile_id == profile_id]
        completed = sum(1 for i in indices if self.is_objective_complete(mission_id, i))
        return (completed, len(indices))

    def group_objective_progress(self, mission_id: str) -> tuple[int, int]:
        """(completed, total) across EVERY objective on this Mission —
        personal and shared alike — the vision doc's own "Household
        Progress: 68%" example."""
        mission = self.get_mission(mission_id)
        if mission is None:
            return (0, 0)
        completed = sum(1 for i in range(len(mission.objectives)) if self.is_objective_complete(mission_id, i))
        return (completed, len(mission.objectives))

    def _trip_elapsed_hours(self, trip_id: str) -> Optional[float]:
        trip = self.context.trips.get_trip(trip_id)
        if trip is None or len(trip.splits) < 2:
            return None
        timestamps = sorted(datetime.fromisoformat(s.logged_at) for s in trip.splits)
        return (timestamps[-1] - timestamps[0]).total_seconds() / 3600.0

    # ------------------------------------------------------------------
    # Auto-assignment — "MIA should assign me missions sometimes"
    # ------------------------------------------------------------------

    def check_for_auto_assignment(self) -> Optional[Mission]:
        """
        Called periodically by core/application.py (same always-alive
        QTimer pattern as `_check_daily_occasions`) — see this module's
        own docstring for the two rules this runs, in priority order.
        Creates and returns at most one auto-assigned Mission per call;
        returns None if neither rule's conditions are currently met.
        """
        mission = self._check_idle_rule()
        if mission is not None:
            return mission
        return self._check_stale_task_rule()

    def _check_idle_rule(self) -> Optional[Mission]:
        if any(m.status == "active" for m in self._missions):
            return None

        mia_assigned = [m for m in self._missions if m.assigned_by == "mia"]
        if mia_assigned:
            most_recent = max(mia_assigned, key=lambda m: m.created_at)
            age_days = (datetime.now() - datetime.fromisoformat(most_recent.created_at)).total_seconds() / 86400.0
            if age_days < _AUTO_ASSIGN_IDLE_DAYS:
                return None

        used_names = {m.name for m in self._missions}
        template = next(
            (t for t in _AUTO_MISSION_TEMPLATES if t[0] not in used_names),
            _AUTO_MISSION_TEMPLATES[0],  # every template's been used before — just cycle back to the first
        )
        name, objective_specs = template
        mission = self.add_mission(name=name, assigned_by="mia")
        for description, metric_type, target in objective_specs:
            self.add_objective(mission.mission_id, description, metric_type, target)
        self._notify_mission_auto_assigned(mission)
        return mission

    def _check_stale_task_rule(self) -> Optional[Mission]:
        if self.context.tasks is None:
            return None

        wrapped_task_ids = {m.task_id for m in self._missions if m.task_id is not None}
        now = datetime.now()
        candidates = [
            task
            for task in self.context.tasks.all_tasks()
            if not task.done and task.task_id not in wrapped_task_ids and task.updated_at
        ]
        if not candidates:
            return None

        stalest = min(candidates, key=lambda t: t.updated_at)
        age_days = (now - datetime.fromisoformat(stalest.updated_at)).total_seconds() / 86400.0
        if age_days < _STALE_TASK_DAYS:
            return None

        mission = self.add_mission(name=f"Finally Finish: {stalest.title}", task_id=stalest.task_id, assigned_by="mia")
        self.add_objective(mission.mission_id, f'Complete "{stalest.title}"', "task_done", 1.0)
        self._notify_mission_auto_assigned(mission)
        return mission

    def _notify_mission_auto_assigned(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F4DC MIA has a new mission for you",
            message=f"\"{mission.name}\" — accept the challenge, or abandon it if it's not for you right now.",
            level="info",
            source="missions",
        )
