"""
core.mission_manager
=======================

Missions/Gamification — docs/ROADMAP.md milestone v0.18, the second of
three new subsystems from the 2026-07-14 wearable-companion vision
update (see docs/VISION.md). Turns a stated goal/hobby into a tracked
Mission with one or more Objectives (e.g. a "Master Angler" mission for
a fishing trip: one objective for time spent fishing, one for fish
caught). Same persisted-JSON pattern as core/expedition_manager.py:
data/missions.json, dataclasses with to_dict/from_dict, a manager class
wrapping load/save. `Objective` is nested inside `Mission`'s own JSON,
not a separate top-level record — same reasoning as `GearItem`/`Split`
nested inside `Trip` (core/trip_manager.py): an objective only ever
makes sense in the context of one mission.

A Mission optionally links to an existing `core.trip_manager.Trip` via
`trip_id` (mirrors `JournalEntry.trip_id`'s optional-FK pattern) —
`trip_id=None` supports a general goal not tied to any specific outing
("finish wiring the garage"), not just outdoor Trip-scoped ones.
`task_id` is the same idea for `core.task_manager.Task` — used only by
`check_for_auto_assignment()`'s "stale task" rule below.

Three objective metric types (`METRIC_TYPES`, same fixed-vocabulary
pattern as `ACTIVITY_TYPES`):
- `"tally"` — a manually-incremented counter (fish caught, species
  identified, etc.) — the one genuinely new primitive this milestone
  needed, since nothing else in the app models an arbitrary count.
  `Objective.progress` stores this directly.
- `"trip_duration_hours"` — computed on demand from the linked Trip's
  logged splits (first-to-last-split elapsed time), never stored, so
  it can't go stale — same "compute on demand" philosophy as
  core/memory_manager.py's ExpeditionRecap. Requires the Mission to
  have a `trip_id` and that Trip to have at least 2 logged splits;
  reads as 0.0 (not started) otherwise rather than raising, since an
  objective with no progress yet is a normal, expected state.
- `"task_done"` — same "compute on demand, never stored" philosophy as
  `trip_duration_hours`, reading the linked `core.task_manager.Task`
  (via the Mission's `task_id`)'s `done` flag as 1.0/0.0. Only ever
  produced by `check_for_auto_assignment()`'s "stale task" rule — there
  is no UI for a user to create one of these by hand, since a task's
  own checkbox is already the natural way to mark it done.

**2026-07-16 gamification pass** (docs/VISION.md's "gamifying life"
goal, at the user's explicit request: "MIA should assign me missions
sometimes... there's not much fun in having to assign yourself
missions"): `Mission.assigned_by` ("user" | "mia") records whether a
Mission was hand-created via modules/missions/module.py's "Add Mission"
button or auto-generated by `check_for_auto_assignment()`, so
gui/widgets/mission_card.py can show a distinct badge for the latter.

`check_for_auto_assignment()` is deliberately rule-based, not
LLM-driven — CLAUDE.md's "no AI/assistant logic yet" scope (ROADMAP
phase v0.5) rules out anything smarter for now, and a handful of
deterministic, fully-offline, testable-without-a-model rules already
satisfy "MIA assigns me missions sometimes":

1. **Idle rule**: if there's no currently-active mission, and either no
   mission has ever been auto-assigned before or it's been at least
   `_AUTO_ASSIGN_IDLE_DAYS` since the last one was, MIA picks the next
   not-yet-used template from `_AUTO_MISSION_TEMPLATES` (cycling back to
   the start once every template has been used at least once) and
   assigns it.
2. **Stale task rule**: otherwise, if `context.tasks` is available, MIA
   looks for the least-recently-updated incomplete Task that isn't
   already wrapped by an existing Mission's `task_id`, and — only once
   it's sat untouched for at least `_STALE_TASK_DAYS` — turns it into a
   one-objective Mission (`metric_type="task_done"`), so a task that's
   been quietly ignored gets a nudge as "MIA turning it into a quest"
   rather than the user having to notice and self-assign it.

Only one Mission is auto-assigned per `check_for_auto_assignment()`
call (whichever rule fires first), and it's driven off dates already
stored on real records (mission/task `created_at`/`updated_at`) rather
than a new "last checked" timestamp — same "derive it, don't add a new
field to track it" preference as `core/daily_occasions.py`'s own
once-daily gates use the target date field itself, not a separate
counter.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.app_context import AppContext
from core.gamification import SkillWeight
from core.logger import get_logger

log = get_logger(__name__)

_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_MISSIONS_FILE = _DATA_DIR / "missions.json"

METRIC_TYPES: tuple[str, ...] = ("tally", "trip_duration_hours", "task_done")

# check_for_auto_assignment()'s two rule thresholds — see this module's
# own "2026-07-16 gamification pass" docstring section above.
_AUTO_ASSIGN_IDLE_DAYS = 3
_STALE_TASK_DAYS = 5

# Flavorful, fully self-contained (no other manager needed) mission
# templates for the "idle" auto-assignment rule — deliberately generic
# life-gamification goals rather than anything tied to a specific
# module, since check_for_auto_assignment() has no way to know what the
# user actually cares about right now without real AI/assistant logic
# (out of scope — see CLAUDE.md). Each entry: (name, [(description,
# metric_type, target), ...]) — always "tally" here since these have no
# linked Trip/Task to compute a live metric from.
_AUTO_MISSION_TEMPLATES: tuple[tuple[str, tuple[tuple[str, str, float], ...]], ...] = (
    (
        "Digital Declutter",
        (("Clear out 10 old files, photos, or downloads you no longer need", "tally", 10.0),),
    ),
    (
        "Deep Work Streak",
        (("Log 3 focused work sessions with no distractions", "tally", 3.0),),
    ),
    (
        "Tidy Up",
        (("Straighten up 3 areas of your space", "tally", 3.0),),
    ),
    (
        "Move Your Body",
        (("Get up and move around 5 separate times today", "tally", 5.0),),
    ),
    (
        "Inbox Zero Push",
        (("Clear 15 messages/emails out of your inbox", "tally", 15.0),),
    ),
)


@dataclass
class Objective:
    description: str  # e.g. "Catch 3 fish" or "Spend 2 hours fishing"
    metric_type: str  # one of METRIC_TYPES
    target: float
    progress: float = 0.0  # only meaningful for "tally" — "trip_duration_hours" is always computed live, never stored here

    def to_dict(self) -> dict:
        return {
            "description": self.description,
            "metric_type": self.metric_type,
            "target": self.target,
            "progress": self.progress,
        }

    @staticmethod
    def from_dict(data: dict) -> "Objective":
        return Objective(
            description=data.get("description", ""),
            metric_type=data.get("metric_type", "tally"),
            target=float(data.get("target", 0.0)),
            progress=float(data.get("progress", 0.0)),
        )


#: Suggested vocabulary for Mission.difficulty — a plain str, not an
#: enum, same "unrecognized/blank just means unspecified" reasoning as
#: core/trip_manager.py's ACTIVITY_TYPES.
DIFFICULTY_LEVELS: tuple[str, ...] = ("EASY", "NORMAL", "HARD")


@dataclass
class Mission:
    mission_id: str
    name: str
    trip_id: Optional[str] = None
    task_id: Optional[str] = None
    # Connective-infrastructure pass (2026-09-11) — a Mission can
    # optionally be the gamified "face" of a Project, rather than the
    # two staying two unrelated containers for structured work. None
    # by default (zero migration needed for existing data/missions.json)
    # and, deliberately, not settable through update_mission() once a
    # Mission exists — same "pick it at creation, don't reassign later"
    # rule trip_id already follows.
    project_id: Optional[str] = None
    status: str = "active"  # "active" | "completed" | "abandoned"
    assigned_by: str = "user"  # "user" | "mia" — see module docstring's "2026-07-16 gamification pass"
    objectives: list[Objective] = field(default_factory=list)
    created_at: str = ""  # ISO datetime
    updated_at: str = ""  # ISO datetime
    # 2026-07-18 design handoff (CCH.zip's Mission Log screen) — cosmetic/
    # gamification fields the redesigned Missions module surfaces.
    # `region` is a short mono "eyebrow" label (e.g. "FIELD SEASON ·
    # FISHING"), not a real geographic region — free text, same "just a
    # label" spirit as Trip.activity_type.
    icon: str = "\U0001F4CB"  # clipboard, matches this project's emoji-glyph convention (no image assets)
    region: str = ""
    summary: str = ""  # longer descriptive paragraph, shown on the Mission Log detail card
    difficulty: str = "NORMAL"
    mission_type: str = "OPTIONAL MISSION"  # e.g. "OPTIONAL MISSION", "DAILY MISSION" — free text, shown as-is
    reward_xp: int = 0
    reward_credits: int = 0
    # "My Hero's Path" (2026-09-11) — optional per-skill XP a completed
    # Mission also grants, alongside its existing flat reward_xp, via
    # the same core.gamification.grant_xp() path every routine-
    # completion hook already uses. Empty by default: every Mission
    # created before this pass deserializes with skill_rewards=[] and
    # behaves exactly as it did — no migration needed. Same "a record
    # owns its own nested list of sub-items" shape as `objectives`
    # above, not a separate top-level manager.
    skill_rewards: list[SkillWeight] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "mission_id": self.mission_id,
            "name": self.name,
            "trip_id": self.trip_id,
            "task_id": self.task_id,
            "project_id": self.project_id,
            "status": self.status,
            "assigned_by": self.assigned_by,
            "objectives": [o.to_dict() for o in self.objectives],
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "icon": self.icon,
            "region": self.region,
            "summary": self.summary,
            "difficulty": self.difficulty,
            "mission_type": self.mission_type,
            "reward_xp": self.reward_xp,
            "reward_credits": self.reward_credits,
            "skill_rewards": [{"skill_id": w.skill_id, "xp": w.xp} for w in self.skill_rewards],
        }

    @staticmethod
    def from_dict(data: dict) -> "Mission":
        return Mission(
            mission_id=data.get("mission_id", uuid.uuid4().hex[:10]),
            name=data.get("name", ""),
            trip_id=data.get("trip_id"),
            task_id=data.get("task_id"),
            project_id=data.get("project_id"),
            status=data.get("status", "active"),
            assigned_by=data.get("assigned_by", "user"),
            objectives=[Objective.from_dict(d) for d in data.get("objectives", [])],
            created_at=data.get("created_at", ""),
            updated_at=data.get("updated_at", ""),
            icon=data.get("icon", "\U0001F4CB"),
            region=data.get("region", ""),
            summary=data.get("summary", ""),
            difficulty=data.get("difficulty", "NORMAL"),
            mission_type=data.get("mission_type", "OPTIONAL MISSION"),
            reward_xp=data.get("reward_xp", 0),
            reward_credits=data.get("reward_credits", 0),
            skill_rewards=[
                SkillWeight(skill_id=d["skill_id"], xp=d["xp"]) for d in data.get("skill_rewards", [])
            ],
        )


class MissionManager:
    def __init__(self, context: AppContext) -> None:
        self.context = context
        self._missions: list[Mission] = []
        self._load()

    # ------------------------------------------------------------------
    # Persistence
    # ------------------------------------------------------------------

    def _load(self) -> None:
        if not _MISSIONS_FILE.exists():
            self._missions = []
            return
        try:
            raw = json.loads(_MISSIONS_FILE.read_text(encoding="utf-8"))
            self._missions = [Mission.from_dict(d) for d in raw]
        except (json.JSONDecodeError, OSError):
            log.exception("Failed to load missions.json — starting with an empty list.")
            self._missions = []

    def _save(self) -> None:
        _DATA_DIR.mkdir(parents=True, exist_ok=True)
        _MISSIONS_FILE.write_text(
            json.dumps([m.to_dict() for m in self._missions], indent=2),
            encoding="utf-8",
        )

    def _bump_updated_at(self, mission: Mission) -> None:
        mission.updated_at = datetime.now().isoformat(timespec="seconds")

    # ------------------------------------------------------------------
    # Mission CRUD
    # ------------------------------------------------------------------

    def add_mission(
        self,
        name: str,
        trip_id: Optional[str] = None,
        task_id: Optional[str] = None,
        project_id: Optional[str] = None,
        assigned_by: str = "user",
        icon: str = "\U0001F4CB",
        region: str = "",
        summary: str = "",
        difficulty: str = "NORMAL",
        mission_type: str = "OPTIONAL MISSION",
        reward_xp: int = 0,
        reward_credits: int = 0,
        skill_rewards: Optional[list[SkillWeight]] = None,
    ) -> Mission:
        now = datetime.now().isoformat(timespec="seconds")
        mission = Mission(
            mission_id=uuid.uuid4().hex[:10],
            name=name,
            trip_id=trip_id,
            task_id=task_id,
            project_id=project_id,
            assigned_by=assigned_by,
            created_at=now,
            updated_at=now,
            icon=icon,
            region=region,
            summary=summary,
            difficulty=difficulty,
            mission_type=mission_type,
            reward_xp=reward_xp,
            reward_credits=reward_credits,
            skill_rewards=list(skill_rewards) if skill_rewards else [],
        )
        self._missions.append(mission)
        self._save()
        log.info("Mission added: '%s'", name)
        return mission

    def update_mission(self, mission_id: str, **fields) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        was_completed = mission.status == "completed"
        for key, value in fields.items():
            if key in ("created_at", "trip_id", "project_id"):
                raise ValueError(f"'{key}' can't be set through update_mission().")
            if not hasattr(mission, key):
                raise ValueError(f"Mission has no field '{key}'.")
            setattr(mission, key, value)
        self._bump_updated_at(mission)
        self._save()
        # Fires uniformly whether "completed" was set via
        # modules/missions/module.py's own UI button or the Assistant's
        # complete_mission action (core/application.py) — celebration
        # logic lives here, in the manager, so neither call site needs
        # its own copy of "did this just newly become complete."
        if not was_completed and mission.status == "completed":
            self._notify_mission_completed(mission)
            self._credit_mission_rewards(mission)
        return mission

    def _credit_mission_rewards(self, mission: Mission) -> None:
        """
        Credits reward_xp/reward_credits to the active profile — best-
        effort, same graceful-degradation stance as everything else here
        that depends on another manager (no active profile yet, e.g.
        during first-run setup, just means no one to credit).

        "My Hero's Path" (2026-09-11): also credits mission.skill_rewards
        to context.skills, if wired — a completed Mission is a real,
        deliberate completion, not routine CRUD, so it always uses its
        own credit-and-notify logic here rather than routing through
        core.gamification.grant_xp() (which would also fire a second,
        redundant notification on top of _notify_mission_completed()'s
        own).
        """
        if self.context.profiles is None or (
            mission.reward_xp == 0 and mission.reward_credits == 0 and not mission.skill_rewards
        ):
            return
        active_profile = self.context.profiles.get_active_profile()
        if active_profile is None:
            return
        if mission.reward_xp:
            self.context.profiles.add_xp(active_profile.profile_id, mission.reward_xp)
        if mission.reward_credits:
            self.context.profiles.add_credits(active_profile.profile_id, mission.reward_credits)
        if mission.skill_rewards and self.context.skills is not None:
            for weight in mission.skill_rewards:
                self.context.skills.add_skill_xp(active_profile.profile_id, weight.skill_id, weight.xp)

    def delete_mission(self, mission_id: str) -> None:
        self._missions = [m for m in self._missions if m.mission_id != mission_id]
        self._save()

    def get_mission(self, mission_id: str) -> Optional[Mission]:
        for mission in self._missions:
            if mission.mission_id == mission_id:
                return mission
        return None

    def all_missions(self) -> list[Mission]:
        return sorted(self._missions, key=lambda m: m.created_at, reverse=True)

    def missions_for_trip(self, trip_id: str) -> list[Mission]:
        return [m for m in self._missions if m.trip_id == trip_id]

    # ------------------------------------------------------------------
    # Objectives
    # ------------------------------------------------------------------

    def add_objective(self, mission_id: str, description: str, metric_type: str, target: float) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if metric_type not in METRIC_TYPES:
            raise ValueError(f"Unknown metric_type '{metric_type}'.")
        mission.objectives.append(Objective(description=description, metric_type=metric_type, target=target))
        self._bump_updated_at(mission)
        self._save()
        return mission

    def delete_objective(self, mission_id: str, index: int) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if not (0 <= index < len(mission.objectives)):
            raise ValueError(f"Mission '{mission_id}' has no objective at index {index}.")
        del mission.objectives[index]
        self._bump_updated_at(mission)
        self._save()
        return mission

    def increment_tally(self, mission_id: str, index: int, delta: float = 1.0) -> Mission:
        mission = self.get_mission(mission_id)
        if mission is None:
            raise ValueError(f"No mission with id '{mission_id}'.")
        if not (0 <= index < len(mission.objectives)):
            raise ValueError(f"Mission '{mission_id}' has no objective at index {index}.")
        objective = mission.objectives[index]
        if objective.metric_type != "tally":
            raise ValueError(f"Objective '{objective.description}' is not a tally-type objective.")
        was_objective_complete = objective.progress >= objective.target
        all_were_complete = self._all_objectives_complete(mission)
        objective.progress += delta
        self._bump_updated_at(mission)
        self._save()

        is_objective_complete = objective.progress >= objective.target
        if not was_objective_complete and is_objective_complete:
            self._notify_objective_completed(mission, objective)
        if not all_were_complete and self._all_objectives_complete(mission):
            self._notify_all_objectives_completed(mission)
        return mission

    def _all_objectives_complete(self, mission: Mission) -> bool:
        """
        Uses is_objective_complete() (not a bare progress>=target check
        here) so a mixed mission — some tally objectives, some
        trip_duration_hours ones — is judged correctly on both metric
        types, not just tally's directly-stored progress.
        """
        if not mission.objectives:
            return False
        return all(
            self.is_objective_complete(mission.mission_id, index) for index in range(len(mission.objectives))
        )

    def _notify_objective_completed(self, mission: Mission, objective: Objective) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F3C6 Objective complete!",
            message=f"You did it! \"{objective.description}\" is complete on your \"{mission.name}\" mission. Keep it up!",
            level="info",
            source="missions",
        )

    def _notify_all_objectives_completed(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F3C6 All objectives complete!",
            message=f"Every objective on \"{mission.name}\" is done — amazing work! Ready to mark it complete?",
            level="info",
            source="missions",
        )

    def _notify_mission_completed(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F389 Mission complete!",
            message=f"\"{mission.name}\" is complete! That's a real achievement — what's next?",
            level="info",
            source="missions",
        )

    def objective_progress(self, mission_id: str, index: int) -> Optional[float]:
        mission = self.get_mission(mission_id)
        if mission is None or not (0 <= index < len(mission.objectives)):
            return None
        objective = mission.objectives[index]
        if objective.metric_type == "trip_duration_hours":
            if mission.trip_id is None:
                return 0.0
            return self._trip_elapsed_hours(mission.trip_id) or 0.0
        if objective.metric_type == "task_done":
            if mission.task_id is None or self.context.tasks is None:
                return 0.0
            task = self.context.tasks.get_task(mission.task_id)
            return 1.0 if (task is not None and task.done) else 0.0
        return objective.progress

    def is_objective_complete(self, mission_id: str, index: int) -> bool:
        mission = self.get_mission(mission_id)
        if mission is None or not (0 <= index < len(mission.objectives)):
            return False
        progress = self.objective_progress(mission_id, index)
        return progress is not None and progress >= mission.objectives[index].target

    def _trip_elapsed_hours(self, trip_id: str) -> Optional[float]:
        trip = self.context.trips.get_trip(trip_id)
        if trip is None or len(trip.splits) < 2:
            return None
        timestamps = sorted(datetime.fromisoformat(s.logged_at) for s in trip.splits)
        return (timestamps[-1] - timestamps[0]).total_seconds() / 3600.0

    # ------------------------------------------------------------------
    # Auto-assignment — "MIA should assign me missions sometimes"
    # ------------------------------------------------------------------

    def check_for_auto_assignment(self) -> Optional[Mission]:
        """
        Called periodically by core/application.py (same always-alive
        QTimer pattern as `_check_daily_occasions`) — see this module's
        own docstring for the two rules this runs, in priority order.
        Creates and returns at most one auto-assigned Mission per call;
        returns None if neither rule's conditions are currently met.
        """
        mission = self._check_idle_rule()
        if mission is not None:
            return mission
        return self._check_stale_task_rule()

    def _check_idle_rule(self) -> Optional[Mission]:
        if any(m.status == "active" for m in self._missions):
            return None

        mia_assigned = [m for m in self._missions if m.assigned_by == "mia"]
        if mia_assigned:
            most_recent = max(mia_assigned, key=lambda m: m.created_at)
            age_days = (datetime.now() - datetime.fromisoformat(most_recent.created_at)).total_seconds() / 86400.0
            if age_days < _AUTO_ASSIGN_IDLE_DAYS:
                return None

        used_names = {m.name for m in self._missions}
        template = next(
            (t for t in _AUTO_MISSION_TEMPLATES if t[0] not in used_names),
            _AUTO_MISSION_TEMPLATES[0],  # every template's been used before — just cycle back to the first
        )
        name, objective_specs = template
        mission = self.add_mission(name=name, assigned_by="mia")
        for description, metric_type, target in objective_specs:
            self.add_objective(mission.mission_id, description, metric_type, target)
        self._notify_mission_auto_assigned(mission)
        return mission

    def _check_stale_task_rule(self) -> Optional[Mission]:
        if self.context.tasks is None:
            return None

        wrapped_task_ids = {m.task_id for m in self._missions if m.task_id is not None}
        now = datetime.now()
        candidates = [
            task
            for task in self.context.tasks.all_tasks()
            if not task.done and task.task_id not in wrapped_task_ids and task.updated_at
        ]
        if not candidates:
            return None

        stalest = min(candidates, key=lambda t: t.updated_at)
        age_days = (now - datetime.fromisoformat(stalest.updated_at)).total_seconds() / 86400.0
        if age_days < _STALE_TASK_DAYS:
            return None

        mission = self.add_mission(name=f"Finally Finish: {stalest.title}", task_id=stalest.task_id, assigned_by="mia")
        self.add_objective(mission.mission_id, f'Complete "{stalest.title}"', "task_done", 1.0)
        self._notify_mission_auto_assigned(mission)
        return mission

    def _notify_mission_auto_assigned(self, mission: Mission) -> None:
        if self.context.notifications is None:
            return
        self.context.notifications.notify(
            title="\U0001F4DC MIA has a new mission for you",
            message=f"\"{mission.name}\" — accept the challenge, or abandon it if it's not for you right now.",
            level="info",
            source="missions",
        )
