"""
tools.dump_assistant_capabilities
====================================

Regenerates `docs/ASSISTANT_CAPABILITIES.md`'s tool-registry table
directly from the real, live `AssistantActionRegistry`
(`core/application.py`'s `_register_assistant_actions()`) — never
hand-typed, so this can't silently drift the way a hand-maintained list
would (this project has hit that exact staleness failure mode with
other docs before). Run this any time the Assistant's action registry
changes (a new action added/removed/re-described) and paste the output
over the "Tool registry" section of `docs/ASSISTANT_CAPABILITIES.md`.

Read-only — constructs a real `MIAApplication` (needed because actions
are registered as a side effect of full app construction) but never
calls `.save()`/any handler, so it doesn't touch real config/data.
Run with the real Ollama server does NOT need to be up — this only
introspects registered metadata, no LLM calls happen.

Usage:
    python tools/dump_assistant_capabilities.py
"""

from __future__ import annotations

import collections
import os
import sys

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.application import MIAApplication  # noqa: E402


def main() -> None:
    app = MIAApplication()
    registry = app.context.assistant_actions
    actions = list(registry._actions.values())

    by_domain = collections.defaultdict(list)
    for action in actions:
        by_domain[action.domain].append(action)

    print(f"<!-- Generated by tools/dump_assistant_capabilities.py — {len(actions)} actions, {len(by_domain)} domains -->")
    print()
    for domain in sorted(by_domain):
        domain_actions = sorted(by_domain[domain], key=lambda a: a.name)
        print(f"### `{domain}` ({len(domain_actions)})")
        print()
        print("| Action | Destructive | Description |")
        print("|---|---|---|")
        for action in domain_actions:
            destructive = "Yes" if action.destructive else ""
            description = action.description.replace("|", "\\|")
            print(f"| `{action.name}` | {destructive} | {description} |")
        print()


if __name__ == "__main__":
    main()
